"""
Reports Module
==============
Defines the Pydantic schemas for the final structured case reports.
This ensures strict validation of the LLM's JSON output.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class CaseReport(BaseModel):
    """
    Structured output generated by the LangGraph agent after
    investigating a flagged event.
    """
    case_id: str = Field(description="The unique identifier for this investigation case (typically same as event_id).")
    fraud_type: str = Field(description="The classified type of fraud (e.g., Synthetic Identity, Account Takeover).")
    confidence: float = Field(description="Confidence score of the classification (0.0 to 1.0).", ge=0.0, le=1.0)
    evidence_summary: str = Field(description="A concise summary of the evidence supporting the classification.")
    similar_cases: List[str] = Field(default_factory=list, description="List of historical case IDs that are similar to this event.")
    recommended_action: str = Field(description="The recommended action for the human reviewer (e.g., Escalate, Block, Dismiss).")
    reviewer_notes: Optional[str] = Field(default="", description="Empty field for the human reviewer to add notes later.")
